### ISSUE TITLE
Regarding DataSet

### ISSUE THREAD

**Issue by r-anupama** [escapa12/carotidsTFM#1]
Hi, 
I am doing some research over Carotid Artery  Segmentation and IMT with Machine Learning.Its been hard to find the Carotid Artery Segmentation dataset. 
for my Research Purpose can you share the datasets used for the Training.
 @enricsarle @lauraigual @escapa12

**Comment by enricsarle** [comment]
Hi,
Medical images can no be freely shared. Two research groups share with us theirs datasets to do this study. You can find more information of the dataset and the research groups on the report https://github.com/escapa12/carotidsTFM/blob/master/TFM_Project_Report.pdf
