### ISSUE TITLE
The links to the datasets are not available

### ISSUE THREAD

**Issue by Leong1230** [escapa12/carotidsTFM#2]
Hi! Thank you for sharing the great work!
I have been recently working on carotid artery ultrasound segmentaion and looking for related datasets. But I fail to open the the links to [REGICOR](https://www.regicor.org/) and [NEFRONA](http://www.nefrona.es/). Are they still open-source? Are there any available sources that I can download from?
Looking forward to your response~

**Comment by enricsarle** [comment]
Data was no open-source. I updated the links to the data providers (https://regicor.cat/ and https://www.udetma.com/es/proyecto-nefrona/proyecto.html)
